# Generated by Django 3.0.5 on 2020-04-17 09:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=1000, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='five_starred_recipes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=1000, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='four_starred_recipes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=1000, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=1000, null=True), size=None),
        ),
    ]
