# Generated by Django 3.0.5 on 2020-04-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20200417_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='five_starred_recipes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='four_starred_recipes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='health_labels',
        ),
    ]
