# Generated by Django 3.0.5 on 2020-04-17 14:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=500, null=True)),
                ('main_protein', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=5000, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('instructions_url', models.CharField(max_length=500, null=True)),
                ('servings', models.IntegerField(null=True)),
                ('diet_Labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('health_Labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('ingredients_lines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('calories', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('fat_unit', models.CharField(max_length=100, null=True)),
                ('sat_fat', models.FloatField(null=True)),
                ('sat_fat_unit', models.CharField(max_length=100, null=True)),
                ('trans_fat', models.FloatField(null=True)),
                ('trans_fat_unit', models.CharField(max_length=100, null=True)),
                ('carbs', models.FloatField(null=True)),
                ('carbs_unit', models.CharField(max_length=100, null=True)),
                ('sugars', models.FloatField(null=True)),
                ('sugars_unit', models.CharField(max_length=100, null=True)),
                ('protein', models.FloatField(null=True)),
                ('protein_unit', models.CharField(max_length=100, null=True)),
                ('cholesterol', models.FloatField(null=True)),
                ('cholesterol_unit', models.CharField(max_length=100, null=True)),
                ('sodium', models.FloatField(null=True)),
                ('sodium_unit', models.CharField(max_length=100, null=True)),
                ('calcium', models.FloatField(null=True)),
                ('calcium_unit', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_num', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='health_labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('recipe_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Recipe')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
