# Generated by Django 3.0.5 on 2020-04-17 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=500, null=True)),
                ('main_protein', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=5000, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('instructions_url', models.CharField(max_length=500, null=True)),
                ('servings', models.IntegerField(null=True)),
                ('diet_Labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('health_Labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('ingredients_lines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('calories', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('fat_unit', models.CharField(max_length=100, null=True)),
                ('sat_fat', models.FloatField(null=True)),
                ('sat_fat_unit', models.CharField(max_length=100, null=True)),
                ('trans_fat', models.FloatField(null=True)),
                ('trans_fat_unit', models.CharField(max_length=100, null=True)),
                ('carbs', models.FloatField(null=True)),
                ('carbs_unit', models.CharField(max_length=100, null=True)),
                ('sugars', models.FloatField(null=True)),
                ('sugars_unit', models.CharField(max_length=100, null=True)),
                ('protein', models.FloatField(null=True)),
                ('protein_unit', models.CharField(max_length=100, null=True)),
                ('cholesterol', models.FloatField(null=True)),
                ('cholesterol_unit', models.CharField(max_length=100, null=True)),
                ('sodium', models.FloatField(null=True)),
                ('sodium_unit', models.CharField(max_length=100, null=True)),
                ('calcium', models.FloatField(null=True)),
                ('calcium_unit', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
