# Generated by Django 3.0.5 on 2020-04-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_healthlabel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthLabel',
        ),
    ]
