# Generated by Django 3.0.5 on 2020-04-21 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200420_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_to_buy_for',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_to_buy_for', to='main.Recipe'),
        ),
        migrations.CreateModel(
            name='Meal_plan_recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipes', to='main.Recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
