# Generated by Django 3.0.5 on 2020-04-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200421_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_plan_recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
